### PR TITLE
Add etcd-diagnosis into the tool list

### PR DESCRIPTION
**Pull request by ahrtr**
[etcd-diagnosis](https://github.com/ahrtr/etcd-diagnosis) is an one-stop etcd diagnosis tool. It diagnoses running etcd clusters and generates a report with just one command.

### CODE REVIEW

**Review by serathius — CHANGES_REQUESTED** [review]
I'm semi confident on listing 1 day old projects even if the tool was created by maintainer. I would also prefer that we discuss creation of such tools as community so we can discuss the etcd debuggability gaps so the project can address it directly. 

Let's discuss such tools in the community meeting, if you can attend.

**Comment by ahrtr** [comment]
> I'm semi confident on listing 1 day old projects even if the tool was created by maintainer.

If you have concern on the 1 day age, we can wait to see more feedback.

> I would also prefer that we discuss creation of such tools as community

etcd is a ecosystem. Community not only includes the repo under etcd-io, but also tools and libraries listed in [Libraries and tools](https://etcd.io/docs/v3.5/integrations/).

> Let's discuss such tools in the community meeting

I am not planning to discuss it on the community meeting for now. 

> if you can attend.

I can

**Comment by ahrtr** [comment]
Thanks @spzala for the review comment, which overall makes sense to me. Please also see my responses below for a couple of detailed items.

> if @ahrtr has plan to donate it to the community, that's great. 

Yes, I thought about the same thing each time when I was creating a tool; but did not find a right place or approach to integrate them into the etcd. I'm open to suggestions for any detailed directions. It's also better to get more feedback on the tool before we make any decision.

> May be we can mention in the description that the tool is not tested by a wide user base and feedback are welcome

Thanks for the suggestion.  I think the 1-day (2 days now:)) age has already indicated that it isn't widely used so far:)

> Also, I have one more suggestion to avoid the word "one-stop" in the description. Thanks!

Could you please explain this more? "One-stop" is the goal. :)

**Comment by ptabor** [comment]
1. I wouldn't rule it by age. I would propose spending 5min to try it and asses whether it mets 'quality bar'. 
2. The fact that it's provided by maintainer, gives high confidence it's not 'scam' type of tool, way higher we have about many other tools listed there. 
3. I'm not native speaker: 'one-stop' is not obvious to me.  'comprehensive' or 'automated'  would be cleaner.

**Comment by spzala** [comment]
> Thanks @spzala for the review comment, which overall makes sense to me. Please also see my responses below for a couple of detailed items.
> 
> > if @ahrtr has plan to donate it to the community, that's great.
> 
> Yes, I thought about the same thing each time when I was creating a tool; but did not find a right place or approach to integrate them into the etcd. I'm open to suggestions for any detailed directions. It's also better to get more feedback on the tool before we make any decision.
> 
> > May be we can mention in the description that the tool is not tested by a wide user base and feedback are welcome
> 
> Thanks for the suggestion. I think the 1-day (2 days now:)) age has already indicated that it isn't widely used so far:)
> 
> > Also, I have one more suggestion to avoid the word "one-stop" in the description. Thanks!
> 
> Could you please explain this more? "One-stop" is the goal. :)

Thanks @ahrtr for more details! About replacing "one-stop" :), as @ptabor said it may not be obvious to understand for everyone on the etcd page. I like what he suggested i.e. "A comprehensive tool for etcd diagnosis.." if you like it too?. Continue using "one-stop" on the GitHub project description is fine and up to you and other contributors in the future. About donating the tool, I agree with your thoughts.

**Comment by ahrtr** [comment]
>  "A comprehensive tool for etcd diagnosis.." 

Suggestion accepted. Thanks both @spzala and @ptabor

**Review by spzala — APPROVED** [review]
Thanks @ahrtr 
lgtm

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @ahrtr 

In relation to the discussion above, it's not uncommon for utilities like this to become a core/integrated part of a project after initially being created as a separate project and that's always a pathway we can take with this if deemed useful enough.

Of course it's always a nice idea to discuss creating additional tooling with the community before charging ahead and creating it, however it's possible for that to slow innovation and community members are always encouraged to experiment and iterate.

**Comment by ahrtr** [comment]
thx @spzala and @jmhbnz for the review. I am not going to waste time on track this PR, so closing it...

**Pull request closed without merging**
