### PR TITLE
Welcome blog post

### PR DESCRIPTION
**Pull request by lucperkins**
I feel like the blog could use a brief "kick-off" post. Preview here:

https://deploy-preview-56--etcd.netlify.com/blog/welcome/

### CODE REVIEW

**Comment by philips** [comment]
Formatting looks weird to me. 
Screen Shot 2019-12-17 at 2 43 06 PM

cc @jberkus

**Comment by lucperkins** [comment]
@philips Fixed

**Comment by philips** [comment]
looks fine to me

**Comment by philips** [comment]
go ahead and merge @lucperkins

**Comment by lucperkins** [comment]
I've removed the welcome post but kept the minor aesthetic changes, as the Jepsen blog post will be the first

**Pull request merged**
