### PR TITLE
Adding Google Search

### PR DESCRIPTION
**Pull request by nate-double-u**
Adding Google Search by the [Docsy theme method](https://www.docsy.dev/docs/adding-content/navigation/#configure-search-with-a-google-custom-search-engine).

Deploy preview: https://deploy-preview-392--etcd.netlify.app/

fixes: https://github.com/etcd-io/website/issues/340

_Note_: Since there is an alternate solution being proposed, this PR should be closed if https://github.com/etcd-io/website/pull/403 is chosen as the better solution.

### CODE REVIEW

**Comment by nate-double-u** [comment]
To set this up I created a [Google Custom Search Engine](https://cse.google.com/cse/all) (GCSE) to search the site using my @cncf.io Google account.

I can add other google accounts as owners, administrators, etc.
- @spzala, @gyuho, who from the etcd maintainers group should I add?
- @caniszczyk, who from the CNCF/LF should I add (if anyone)?

**Comment by nate-double-u** [comment]
Currently, I've got the whole site available for search -- this includes results from older versions and other static pages (for instance the blog). Is this how the search should be set up? Do we want to only search docs? a specific version of the docs?

**Review by spzala — COMMENTED** [review]
@nate-double-u lgtm but I will ping you to discuss couple review comments/questions early next week. (if changes get reviewed earlier that's good too) Thanks!

**Review by spzala — COMMENTED** [review]
I guess we are going with https://github.com/etcd-io/website/pull/403 Thanks @nate-double-u for the chat.

**Comment by nate-double-u** [comment]
Closing in favour of https://github.com/etcd-io/website/pull/403 as per a conversation with @spzala

**Pull request closed without merging**
