### PR TITLE
Fix paths to client certificates in curl examples

### PR DESCRIPTION
**Pull request by dlax**

### CODE REVIEW

**Review by jmhbnz — CHANGES_REQUESTED** [review]
Thanks for aligning these paths with the rest of the document @dlax. 

Can you please apply the same fix to `content/en/docs/v3.4/op-guide/security.md` and `content/en/docs/v3.6/op-guide/security.md`.

**Comment by dlax** [comment]
> Can you please apply the same fix to `content/en/docs/v3.4/op-guide/security.md` and `content/en/docs/v3.6/op-guide/security.md`.

Done.

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @dlax

**Comment by jmhbnz** [comment]
@spzala this is a minor tweak that just aligns some script paths to ensure the whole document just uses one style, can you please take a look? 🙏🏻

**Review by spzala — APPROVED** [review]
lgtm Thanks @dlax

**Comment by spzala** [comment]
> @spzala this is a minor tweak that just aligns some script paths to ensure the whole document just uses one style, can you please take a look? 🙏🏻

Yes, makes sense! Thank you @jmhbnz

**Comment by spzala** [comment]
Straightforward changes so merging with two reviews.

**Pull request merged**
