### PR TITLE
Migrate documentation: Add docs to etcd-io/website

### PR DESCRIPTION
**Pull request by nate-double-u**
Adding current documentation from https://github.com/etcd-io/etcd/tree/master/Documentation to content/docs/current
- Updating layout files to support new "current" version
- Adding "current" version to deprecation warning (current + latest versions do not have warning)
- Updating config

This addition uses documentation from commit https://github.com/etcd-io/etcd/commit/a4fac14353e701ce78bc4ec6a31e4c923a9e3744

fixes: https://github.com/etcd-io/website/issues/93

## Deploy preview
Homepage: https://deploy-preview-99--etcd.netlify.app/
Docs index: https://deploy-preview-99--etcd.netlify.app/docs/current/
Deprecation sample: https://deploy-preview-99--etcd.netlify.app/docs/v3.3.13/demo/

### CODE REVIEW

**Comment by nate-double-u** [comment]
Last push renames files to use "_" instead of "-" to be consistent with previous versions, like PR https://github.com/etcd-io/website/pull/89, but as we've not published this one yet, we don't need to update the redirects to protect bookmarks.

**Comment by nate-double-u** [comment]
Should we add versioning instructions to this repo's README.md file?

**Comment by spzala** [comment]
> Should we add versioning instructions to this repo's README.md file?

@nate-double-u since the etcd.io shows versioning, we should be fine not adding in the README but I would go with best practices and in line with other CNCF doc repos. We can make that changes later as needed. Thanks!

**Review by spzala — APPROVED** [review]
lgmt
Thanks @nate-double-u

**Comment by nate-double-u** [comment]
The last force-push:
- updates the docs to https://github.com/etcd-io/etcd/commit/b5d11723d1eb2be4a5393bcb7e294af3697d5295
- regenerating api_reference_v3.md

Do we need to include:
- content/docs/current/etcd-mixin/mixin.libsonnet
- content/docs/current/dev-guide/apispec/swagger/rpc.swagger.json

**Comment by nate-double-u** [comment]
last force-push is the same "-", "_" as above -- I'll catch it next time I promise 😅

**Review by jingyih — COMMENTED** [review]
lgtm. Thanks!

**Comment by nate-double-u** [comment]
Thanks everyone!

**Pull request merged**
