### PR TITLE
Document a known issue about the v2 to v3 migration

### PR DESCRIPTION
**Pull request by hongbin**
* Update the 3.4 doc about the known issue of v2 to v3 migration
* Remove v2 migration doc from 3.5 and 3.6

Fixes #8804

### CODE REVIEW

**Comment by ahrtr** [comment]
Context: https://github.com/etcd-io/etcd/issues/8804

**Comment by ahrtr** [comment]
Looks good to me per the discussion in https://github.com/etcd-io/etcd/issues/8804. 

cc @spzala @serathius to double confirm.

**Review by spzala — APPROVED** [review]
Nice work. LGTM
Thanks @hongbin

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you @hongbin

**Pull request merged**
