### PR TITLE
Translate Chinese

### PR DESCRIPTION
**Pull request by winnetcn**
Translate Chinese for etcd.io

### CODE REVIEW

**Comment by nate-double-u** [comment]
Hi @winnetcn & @Demogorgon314, thanks for this. It looks like you've done a lot to translate the site for [etcd.cn](https://etcd.cn/).

I don't think we can accept this PR as is because it is translating the whole site, and changing some important settings for the [etcd.io](https://etcd.io/) site.

However, we are currently going through a [documentation overhaul](https://github.com/etcd-io/website/issues/65) that includes a transition to a Docsy Theme, which I hope will make it easier to manage translation and internationalization work like this.

I'd like to invite you to join the discussion:
* [#etcd-docs](https://cloud-native.slack.com/archives/C01SFAR0Q00) channel on the CNCF slack
* [#etcd](https://kubernetes.slack.com/archives/C3HD8ARJ5) channel on the Kubernetes slack
* [etcd maillist](https://groups.google.com/g/etcd-dev)

**Comment by nate-double-u** [comment]
Related: https://github.com/etcd-io/website/pull/359

**Comment by chalin** [comment]
Thanks for this PR, and for your efforts in translating etcd.io. One of the maintainers (@wenjiaswe) will be reaching out to you. For now we have added a link to etcd.cn to the [Community](https://etcd.io/community/) page.

You might have to make your case at one of the [community meetings](https://docs.google.com/document/d/16XEGyPBisZvmmoIHSZzv__LoyOeluC5a4x353CX0SIM) if you'd like the Chinese version of the pages integrated into this site.

I'll close this PR now since it can't be merged in its current form.

**Comment by wenjiaswe** [comment]
@winnetcn Thanks for your time and effort on this PR, we appreciate this! We might have other contributors and maintainers who would like to work together on the Chinese etcd website, please reach out to me at wenjiazhang519@gmail.com. I speak Mandarin as well. 

非常感谢您的PR，我们这边也有一些同样说中文的etcd程序员愿意一起帮助完善中文的etcd网站，如果你愿意的话欢迎参加我们每个月一次的[community meeting](https://docs.google.com/document/d/16XEGyPBisZvmmoIHSZzv__LoyOeluC5a4x353CX0SIM/edit#), 下一次在7月2日美国太平洋时间上午11点。也可以发邮件给我：wenjiazhang519@gmail.com，我们可以安排更适合中国时间的会议。

cc @wilsonwang371 who is also interested.

**Pull request closed without merging**
