### PR TITLE
Fix/multicluster selection

### PR DESCRIPTION
**Pull request by TomaszSyc**
This PR is fixing issue where in multi cluster dashboard it is unable to choose specific cluster to be show metrics from, because of wrong label being used.

### CODE REVIEW

**Comment by TomaszSyc** [comment]
For sure it would be better, for now, I would like to merge this PR as Prometheus helm chart is pointing to this dashboard definitions (https://github.com/prometheus-community/helm-charts/issues/2069)

**Comment by serathius** [comment]
> For sure it would be better, for now, I would like to merge this PR as Prometheus helm chart is pointing to this dashboard definitions ([prometheus-community/helm-charts#2069](https://github.com/prometheus-community/helm-charts/issues/2069))

Maybe that's the main problem that it points to unmaintained file.

**Comment by jmhbnz** [comment]
Hey @TomaszSyc - Following up as this has been open for a long time, is this pull request still valid given https://github.com/prometheus-community/helm-charts/commit/3c4ae526051925d19776aea75beb0f4464351234?

**Comment by jmhbnz** [comment]
Closing this pull request as the source of truth upstream has been corrected and this file is no longer being depended on, refer https://github.com/prometheus-community/helm-charts/pull/2340.

I have opened https://github.com/etcd-io/website/issues/690 to get the cleanup work done to remove the json blob from the website and improve website grafana docs.

**Pull request closed without merging**
