### PR TITLE
Fixed broken links to etcd/client variants on the integrations page

### PR DESCRIPTION
**Pull request by astromechza**
These links were previously broken and returned 404's.

### CODE REVIEW

**Review by spzala — COMMENTED** [review]
@astromechza hi, the changes look good but can you please rebase and fix the conflict? Thanks!

**Comment by nate-double-u** [comment]
Hi @astromechza & @spzala, with all the folder changes made around issue https://github.com/etcd-io/website/issues/152, i've gone ahead and fixed this issue in https://github.com/etcd-io/website/pull/166.

Thanks for looking into this @astromechza!

**Comment by astromechza** [comment]
Thanks @nate-double-u , sorry for the delay here I’ve been absolutely slammed with other work!

**Comment by nate-double-u** [comment]
No worries about any delays, I just made the update b/c so much else has changed around it :)

**Pull request closed without merging**
