### PR TITLE
Add new adopters to config.toml

### PR DESCRIPTION
**Pull request by lucperkins**
Addresses issue #23.

@philips I've made a quick best guess for the descriptions. Feel free to suggest changes.

### CODE REVIEW

**Comment by philips** [comment]
m3 logo or link is missing https://deploy-preview-25--etcd.netlify.com/

**Comment by lucperkins** [comment]
@philips Done

**Comment by philips** [comment]
If you could use the m3 logo that would be great https://github.com/m3db/m3/tree/master/docs/theme/assets/images

But, LGTM

**Comment by lucperkins** [comment]
@philips

**Pull request merged**
