### PR TITLE
Fix link checking following v3.5 release

### PR DESCRIPTION
**Pull request by chalin**
This change is in the original scope of #332

### CODE REVIEW

**Review by nate-double-u — APPROVED** [review]
Right, I missed the link checker when we did the v3.5 release. Thanks!

**Comment by chalin** [comment]
> Right, I missed the link checker when we did the v3.5 release. Thanks!

Unfortunately this is easy to forget, and should ideally only be a temporary measure, but it'll likely stay as it is until we invest some time in getting another link checker.

Thanks for the review.

**Comment by nate-double-u** [comment]
We may want to open an issue to update the [Releasing a new version of the etcd documentation](https://github.com/etcd-io/website#releasing-a-new-version-of-the-etcd-documentation) section of the README file help remind folks.

**Comment by chalin** [comment]
FYI, I added a note to https://github.com/etcd-io/website/issues/383#issuecomment-880924781.

> We may want to open an issue to update the [Releasing a new version of the etcd documentation](https://github.com/etcd-io/website#releasing-a-new-version-of-the-etcd-documentation) section of the README file help remind folks.

I thought that we had an issue open already. Could you check?

**Comment by nate-double-u** [comment]
I'm not seeing a specific issue for it, but if you've updated #383 I think that's enough.

**Comment by chalin** [comment]
I created #406 to track this (and cross-linked to #383).

**Pull request merged**
