### PR TITLE
content: add v3.4.0 documentation

### PR DESCRIPTION
**Pull request by gyuho**
/cc @philips @hexfusion @spzala @xiang90 @jpbetz @jingyih @wenjiaswe

### CODE REVIEW

**Comment by philips** [comment]
This doesn't look right.

New page:
https://deploy-preview-42--etcd.netlify.com/docs/v3.4.0/

Old page:
https://etcd.io/docs/v3.3.12/

Notice the documentation sections is empty and the categories too.

Do not merge this as-is.

**Comment by gyuho** [comment]
Oh, let me fix

**Comment by lucperkins** [comment]
@gyuho Several months ago I attempted to add the appropriate structure for the `Documentation` folder in the etcd repo: https://github.com/etcd-io/etcd/pull/10615. At this point, it's probably too late to merge those changes painlessly, but that PR can act as a guide for how to restructure here. Most notably, see how the `_index.md` files indicate sections.

**Comment by gyuho** [comment]
@lucperkins @philips Now looks good https://deploy-preview-42--etcd.netlify.com/docs/v3.4.0/

**Pull request merged**
