### PR TITLE
New tool: ETCD Manager

### PR DESCRIPTION
**Pull request by gtamas**
Added a new tool to the "Tools" list:

ETCD Manager is a multi-platform ETCD v3 client. Currently, builds are available form Mac, Wiindows and Linux, but iOS / Android builds will also be added in the future.
It aims to be a modern, efficient and easy to use GUI with full coverage of ETCD APIs / functionality. The first public (beta) release is already available.

### CODE REVIEW

**Comment by philips** [comment]
These docs are generated from the etcd source repo: https://github.com/etcd-io/etcd/blob/master/Documentation/integrations.md

**Comment by philips** [comment]
Please update the source repo instead of the website. Thanks! Closing.

**Comment by gtamas** [comment]
@philips 

OK thanks for the info.  I forked the repo and just opened a new PR. 
Sorry, this is my first commit to ETCD docs, I hope I did it right this time :)

**Comment by gtamas** [comment]
@philips 

I can see that a new version of ETCD has been published recently (3.4.0, cool!). 
I added this tool to the ETCD docs in the main ETCD repo (as you suggested) and my PR was merged. 
However, the "libraries and tools" page on your website seems to be unchanged. The list still doesn't include this tool.

Now I'm a bit confused :). Shouldn't the list of tools reflect my changes now? Do I need to do anything else? 

Thanks in advance!

**Pull request closed without merging**
