### PR TITLE
Etcd and Kubernetes Post added

### PR DESCRIPTION
**Pull request by hrittikhere**
Hey,
I have added the post "Kubernetes Stateful Friend - What’s more to etcd?" according to the discussion on [Twitter](https://twitter.com/etcdio/status/1436288959429099520). Can you please give this a look and let me know? Thanks!

### CODE REVIEW

**Comment by hrittikhere** [comment]
@nate-double-u is there a way to add a canonical URL? A bit new to Hugo and I think it would be good :D

**Comment by nate-double-u** [comment]
Do you mean the markdown for links in Hugo? It's the same as GutHub markdown :)

`[Example link text](https://example.org/)`

**Comment by nate-double-u** [comment]
I think you can use something like [Alias described here](https://gohugo.io/content-management/urls/#aliases); but, I'm not sure I'd recommend it as the previous blog posts have just used the default `<date>/<file-name>` format for their url.

**Comment by hrittikhere** [comment]
Hi @nate-double-u,
I am not sure if that exactly works because can't see the tags even after using the tags.
image

I am having a discussion on [Hugo](https://discourse.gohugo.io/t/how-to-add-cannonical-url-to-a-blog/34670) let's see if something comes up :D 

Thanks for helping!

**Comment by hrittikhere** [comment]
Hey,
The blog is edited and I believe it's ready for review can you please look into it? 

Preview: https://deploy-preview-474--etcd.netlify.app/blog/2021/etcd-and-kubernetes/

/cc @hexfusion @xiang90 @nate-double-u @chalin

**Review by chalin — CHANGES_REQUESTED** [review]
For the benefit of SEO, let's avoid duplicating posts. This shouldn't just be a duplicate post. Instead make it a short introduction ("teaser") to the full article and direct interested readers to the full (canonical) article.

**Comment by hrittikhere** [comment]
Okay, Sounds like a good approach. Let me convert the article to Teaser. Thanks!

**Review by spzala — CHANGES_REQUESTED** [review]
@hrittikhere thanks for the PR but in the etcd community meeting and team discussions in the past we have decided to have author host such a content due to maintenance issues. We decided to create a page on the etcd.io where a link to such a blog can be provided for referencing the content. I have created this issue https://github.com/etcd-io/website/issues/503 @nate-double-u @Somoshree - Please take a look. @hrittikhere hope this sounds good to you, and we can close this PR. Thanks!

**Comment by hrittikhere** [comment]
@spzala we can. Thanks!

**Pull request closed without merging**
