### PR TITLE
Added links to images from static folder

### PR DESCRIPTION
**Pull request by ChaitanyaKaranam**
Signed-off-by: Chaitanya Karanam <karanam.krishna.25@gmail.com>

### CODE REVIEW

**Comment by ChaitanyaKaranam** [comment]
Linked images from ``static`` folder. 

Removed redundant img folder from``content/docs/v3.4.0/learning/img``.

**Comment by ChaitanyaKaranam** [comment]
> @ChaitanyaKaranam thanks for the PR but if I am not mistaken, how are these changes fixing the issue? The GH page shows images fine https://github.com/etcd-io/website/blob/master/content/docs/v3.4.0/learning/design-learner.md
> Did you mean to use the /static/img/client-architecture-balancer-figure-01.png and other images under /static ?
> I don't see images/links working from changes. Can you please take a look it again or help me understand? Thanks!
> /cc @lucperkins any thoughts here? Thanks!

The reference for the images works when you are viewing in the markdown version. 
All the images and links work when they are viewed inside Github.
However, when you look at the website, these images have invalid references. Here's the [example](https://etcd.io/docs/v3.4.0/learning/design-learner/).
All the images under this page have invalid references.
Here's the deployed [version](https://deploy-preview-49--etcd.netlify.com/docs/v3.4.0/learning/design-learner/) with fixes.

**Comment by spzala** [comment]
@ChaitanyaKaranam thanks much! Only other thing that I think of is removing the `learning/img` files. I am not sure if this can create any inconstancy considering the etcd repo has used the folder, https://github.com/etcd-io/etcd/blob/master/Documentation/learning/design-learner.md 
/cc @lucperkins 
Thanks!

**Comment by lucperkins** [comment]
@spzala This is unfortunately a necessary inconsistency that results from a discrepancy between how static site generators work and how GitHub displays information. The materials in the `Documentation` directory in `etcd-io/etcd` act as "raw inputs" and the website is the "output." I'm working on a PR that will make it more clear that readers should use the website and that the `Documentation` directory is not meant to be browsable.

**Comment by spzala** [comment]
@lucperkins I see, thank you! And sorry that your initial PR didn't get reviewers comment but glad that you are working on a simpler replacement of that PR. I will be reviewing it. 
/cc @xiang90 @gyuho @jingyih

**Comment by lucperkins** [comment]
@spzala No problem at all. Just miscommunication and equally my fault 😄 I've been in touch with Josh Berkus and we'll get this resolved soon 👍

**Comment by spzala** [comment]
> @spzala No problem at all. Just miscommunication and equally my fault 😄 I've been in touch with Josh Berkus and we'll get this resolved soon 👍

OK. Thanks @lucperkins !! :)

**Pull request closed without merging**
