### PR TITLE
simplifying docs section titles

### PR DESCRIPTION
**Pull request by nate-double-u**
contributes to: https://github.com/etcd-io/website/issues/178

Simplifying titles on the `docsy` branch, as per https://github.com/etcd-io/website/pull/199#issuecomment-816200890

### CODE REVIEW

**Comment by nate-double-u** [comment]
Deploy previews:
* https://deploy-preview-202--etcd.netlify.app
* https://deploy-preview-202--etcd.netlify.app/docs/next/
* https://deploy-preview-202--etcd.netlify.app/docs/v3.4/
* https://deploy-preview-202--etcd.netlify.app/docs/v3.3/
* https://deploy-preview-202--etcd.netlify.app/docs/v3.2/
* https://deploy-preview-202--etcd.netlify.app/docs/v3.1/
* https://deploy-preview-202--etcd.netlify.app/docs/v2.3/

v3.4 is incorrect b/c of it's being a part of the menu structure. Instead of adding the menu info to the front matter, we should add `Docs` to the menu another way, and link it to the `latest` redirect.

**Comment by chalin** [comment]
I felt it was easier to experiment and submit another PR for evaluation.
@nate-double-u, please see #213

**Comment by nate-double-u** [comment]
closing in favour of https://github.com/etcd-io/website/pull/213

**Pull request closed without merging**
