### PR TITLE
[add] SimplifyNet/Etcd.Microsoft.Extensions.Configuration .NET library link

### PR DESCRIPTION
**Pull request by i4004**

### CODE REVIEW

**Review by jmhbnz — COMMENTED** [review]
Thanks @i4004 - Suggest also updating the `v3.4` docs in this commit unless there is a reason why this library is not recommended for etcd `3.4.x`?

**Comment by i4004** [comment]
Updated.

**Comment by jmhbnz** [comment]
> Updated.

Thanks - Can you please squash commits and ensure your commit is signed so the Developer Certificate of Origin check passes, i.e.

```bash
git reset --soft HEAD~2
git commit -s -m "<message>"
git push --force
```

**Comment by i4004** [comment]
@jmhbnz Hi! it is ready :)

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @i4004

**Pull request merged**
