### PR TITLE
Docsy theme

### PR DESCRIPTION
**Pull request by chalin**
### [Conversion to the Docsy theme](https://github.com/etcd-io/website/issues/134) is complete.

You'll find the preview next and screenshots below:

**Preview**: https://docsy--etcd.netlify.app

@spzala @ptabor @jberkus - PTAL and let @nate-double-u and I know if you find that **_this is good enough to use as a base for continued development_**. 

If there are no objections, we'd like to **merge this by Thursday** (04/22) at the latest so that we can then move ahead with the [implementation of the new IA](https://github.com/etcd-io/website/issues/110), and any further changes that you'd like made to the site.

---

### Screenshots

Homepage:

> image

Site page:

> image

### CODE REVIEW

**Comment by hexfusion** [comment]
Looks amazing thank you @nate-double-u and team. LGTM

**Review by spzala — COMMENTED** [review]
lgtm, great look and feel as we discussed! Thanks @nate-double-u @chalin

**Comment by chalin** [comment]
Wonderful, thanks for the feedback @hexfusion and @spzala!

**Comment by chalin** [comment]
@nate-double-u - can you merge this today (either before or after #203), given that this PR has been open for a week? While I might not get to doing etcd work today, if you can merge before the EOD, I'll be able to make some progress at least as of tomorrow morning (ET).

**Review by nate-double-u — APPROVED** [review]

**Comment by chalin** [comment]
Followup changes will be tracked via #247

**Pull request merged**
