### PR TITLE
Community page

### LINKED ISSUE #306: Create a Community page
- [ ] Create a Community page
- [ ] Add a link to this page to the top nav

### PR DESCRIPTION
**Pull request by chalin**
- Closes #306
- Preview: https://deploy-preview-313--etcd.netlify.app/community/

PTAL @spzala @ptabor @gyuho 

---

### Screenshots

Desktop:

> Screen Shot 2021-05-25 at 14 06 41

---

Mobile:

> Screen Shot 2021-05-25 at 14 07 20

### CODE REVIEW

**Comment by nate-double-u** [comment]
Do we want to include slack in the "Join the conversation" section?
* [#etcd](https://kubernetes.slack.com/archives/C3HD8ARJ5) on Kubernetes slack
* [#etcd-docs](https://cloud-native.slack.com/archives/C01SFAR0Q00) on CNCF slack

**Review by nate-double-u — APPROVED** [review]
Thanks @chalin, this looks great!

**Comment by chalin** [comment]
> Do we want to include slack in the "Join the conversation" section? ...

I was going to hold off on the Slack channels for this first iteration. For example, Kubernetes doesn't even mention Slack in their Community page: https://kubernetes.io/community/ (although it is in the footer. Let's continue this discussion at #306.

**Comment by chalin** [comment]
Thanks for the review and approval Nate. I'm going to merge this now. We can address any comments in a followup PR.

**Pull request merged**
