### PR TITLE
Renaming files to use "_" instead of "-"

### PR DESCRIPTION
**Pull request by nate-double-u**
Renaming files to use "_" instead of "-" to be consistent with previous versions. This corrects the 404 error we're seeing when switching between versions of known existing pages.

I've gone through and think that these two files are the only ones affected by this issue.

fixes: https://github.com/etcd-io/website/issues/88

### CODE REVIEW

**Comment by nate-double-u** [comment]
Latest push adds redirects so as to not break bookmarks with this change.

**Comment by nate-double-u** [comment]
Deploy preview:
- https://deploy-preview-89--etcd.netlify.app/docs/v3.4.0/branch_management/
- https://deploy-preview-89--etcd.netlify.app/docs/v3.4.0/reporting_bugs/

Testing the redirects:
- [x] https://deploy-preview-89--etcd.netlify.app/docs/v3.4.0/branch-management/
- [x] https://deploy-preview-89--etcd.netlify.app/docs/v3.4.0/reporting-bugs/

/cc @spzala

**Comment by spzala** [comment]
@nate-double-u thanks! I was about to report this issue and found you have a PR for it :)

**Review by spzala — APPROVED** [review]
lgtm

**Pull request merged**
