### PR TITLE
API reference update

### PR DESCRIPTION
**Pull request by nate-double-u**
Updating titles, removing front-matter descriptions, dropping weights, updating generated content notice

Contributes to https://github.com/etcd-io/website/issues/330

### CODE REVIEW

**Comment by nate-double-u** [comment]
Note that removing the weights actually puts these pages at the bottom of their lists on the dev-guide pages. If we want these pages at the top, we'll need to reintroduce the weights here.

**Comment by nate-double-u** [comment]
Deploy previews:
- https://deploy-preview-337--etcd.netlify.app/docs/v3.4/dev-guide/
  - https://deploy-preview-337--etcd.netlify.app/docs/v3.4/dev-guide/api_reference_v3/
  - https://deploy-preview-337--etcd.netlify.app/docs/v3.4/dev-guide/api_concurrency_reference_v3/
- https://deploy-preview-337--etcd.netlify.app/docs/next/dev-guide/
  - https://deploy-preview-337--etcd.netlify.app/docs/next/dev-guide/api_reference_v3/
  - https://deploy-preview-337--etcd.netlify.app/docs/next/dev-guide/api_concurrency_reference_v3/

**Review by chalin — APPROVED** [review]
Very nice!

**Comment by chalin** [comment]
Thanks for the deploy previews, they're very helpful. For the future, could you add them to opening comment (by editing it). It'll be easier to miss them (on smaller screens, for example), that way.

**Pull request merged**
