### PR TITLE
Update libraries and tools

### PR DESCRIPTION
**Pull request by suizman**
Include mingchuno/etcd4s library for Scala with V3 support and watch using Akka Stream.

### CODE REVIEW

**Review by nate-double-u — CHANGES_REQUESTED** [review]
Hi @suizman, thanks for this.

We're keeping the older versions mostly as an archive, and try not to change them with new information or links (beyond fixing broken things). Is this info relevant to the `/next` (v3.5) or `/v3.4` versions? If so, could you move this info there?

**Comment by nate-double-u** [comment]
I've opened [an issue](https://github.com/etcd-io/website/issues/287) regarding the build failure. I'm not yet sure what's causing it, but it looks similar to another recent, failing PR.

**Comment by nate-double-u** [comment]
@suizman, @chalin has fixed the preview issues with #274. I expect that this PR would have to be rebased in order to trigger a correct build with the new configuration.

**Comment by suizman** [comment]
Hi @nate-double-u, my bad changing the docs for an older version. Now the change is at the correct version **/v3.4**

**Comment by chalin** [comment]
@suizman - I tweaked the description, hopefully that's ok with you.

**Review by chalin — APPROVED** [review]

**Comment by chalin** [comment]
This change needs to be propagated to `/docs/next`, would you be willing to make that change @suizman? I'll open an issue to track this.

**Pull request merged**
