### PR TITLE
Third-party tools and libraries

### PR DESCRIPTION
**Pull request by spzala**
We should add the note as added in this PR. This will also address the concern and discussion we had in some PRs while adding or keeping third-party tools and libraries in the list.

### CODE REVIEW

**Comment by spzala** [comment]
cc @ahrtr @jmhbnz @nate-double-u @serathius

**Review by ahrtr — APPROVED** [review]
LGTM

thx @spzala

**Review by serathius — APPROVED** [review]

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @spzala

**Review by nate-double-u — APPROVED** [review]
/lgtm

**Pull request merged**
