### PR TITLE
Added etcdutl in docs and modified Quickstart page to have a link to etcdutl

### PR DESCRIPTION
**Pull request by Somoshree**
closes: #309 

Deploy previews:
https://deploy-preview-478--etcd.netlify.app/docs/v3.5/getting-started-with-etcdutl/
https://deploy-preview-478--etcd.netlify.app/docs/v3.5/quickstart/#whats-next

### CODE REVIEW

**Comment by jberkus** [comment]
@chalin 

So the strategy has been to pull off the pieces of the Demo page that actually represent otherwise undocumented topics, and give them their own headers.  Given that, are you OK with this page?  Even if it's man-page-like, it's more documentation on etcdutl than we have in our current docs.

**Comment by chalin** [comment]
Hi @jberkus: I'm ok with the content, but it would be inappropriate to entitle it "Getting started ...". IMHO, this page should instead be under, say, `op-guide/` -- such as `/docs/v3.5/op-guide/cmds/etcdutl` or just `/docs/v3.5/op-guide/etcdutl`.

**Comment by nate-double-u** [comment]
Closing as stale.

**Comment by nate-double-u** [comment]
Please feel free to reopen if you have time to work on this again @Somoshree, we appreciate your efforts!

**Pull request closed without merging**
