### PR TITLE
Adding annotations to v3.5 Table of Contents page

### PR DESCRIPTION
**Pull request by nate-double-u**
As per issue #65 
>     * Documentation TOC - page with an annotated TOC for the documentation and direct links to important pages.

Adding annotation to the docs index/TOC

Contributes to: #247

Deploy Preview:
* https://deploy-preview-386--etcd.netlify.app/docs/v3.5/

### CODE REVIEW

**Comment by nate-double-u** [comment]
We had taken the annotations out during the docsy conversion, but I think that there is a value to having them shown. I think there can be an argument made for updating them and making them more descriptive, but I think that can be work done on individual pages (and since the pages them selves contain the annotation/description, this work can be easily parted out into individual issues.

@chalin, @spzala, what are your thoughts on reintroducing annotations to the index/table of contents page?

**Review by jmhbnz — COMMENTED** [review]
Hey @nate-double-u - Can you please rebase this branch so we can get an updated deploy preview to compare with?  Thanks! 🙏🏻

**Review by chalin — CHANGES_REQUESTED** [review]
I'd vote to leave the section's page list as it was. The compact list is easier to scan and the titles are meaningful enough.

**Comment by spzala** [comment]
Thanks much for your quick feedback @chalin In that case, should we close this ? cc @nate-double-u

**Comment by nate-double-u** [comment]
I agree, we can close this.

**Pull request closed without merging**
