### PR TITLE
Fix wording in the defragmentation section docs

### PR DESCRIPTION
**Pull request by chtvrv**
A wording fix for issue #696

### CODE REVIEW

**Review by jmhbnz — APPROVED** [review]
LGTM - Noting that we normally wouldn't update docs for unsupported versions, in this case < 3.4, however this is simple grammar fix so not an issue if we do imo.

Thanks @chtvrv

**Comment by chtvrv** [comment]
Made a note about unsupported versions, thanks

**Review by ahrtr — APPROVED** [review]

**Comment by jmhbnz** [comment]
Gentle ping @spzala for review and merge.

**Review by serathius — APPROVED** [review]

**Review by spzala — COMMENTED** [review]
lgtm Thanks @jmhbnz

**Pull request merged**
