### PR TITLE
Update website installation instructions to latest release tags

### PR DESCRIPTION
**Pull request by ivanvc**
Update the v3.5 release from v3.5.11 to v3.5.12. While working on #774, I noticed it was outdated.

### CODE REVIEW

**Review by jmhbnz — CHANGES_REQUESTED** [review]
Thanks for keeping this up to date @ivanvc 🙏🏻 

We also need to do a similar bump in `content/en/docs/v3.4/_index.md` if memory serves.

**Comment by ivanvc** [comment]
@jmhbnz I'll address it in this PR if that's ok.

**Comment by jmhbnz** [comment]
/retitle Update website installation instructions to latest release tags

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @ivanvc

**Review by ahrtr — APPROVED** [review]
lgtm

Thanks

**Review by spzala — APPROVED** [review]
Thanks @ivanvc

**Pull request merged**
