### PR TITLE
fixed typo in data_corruption.md file

### LINKED ISSUE #688: Typo
This:
compare it’s persistent 

should be:
compare its persistent

https://etcd.io/docs/v3.5/op-guide/data_corruption/

There are other occurrences on the same page, so I suggest searching your site for all occurrences.

### PR DESCRIPTION
**Pull request by anand346**
closes #688 fixed typo

### CODE REVIEW

**Review by jmhbnz — CHANGES_REQUESTED** [review]
Hi @anand346  - Thanks for fixing this, can you please also update the other instances of this in the following files:

```bash
 ~  Documents  website   fixed-typo  grep -Ri "Leader will compare it's persistent st"
content/en/docs/v3.6/op-guide/data_corruption.md:Leader will compare it's persistent state vs other members and rai
se a CORRUPT ALARM if there is a mismatch.
content/en/docs/v3.5/op-guide/data_corruption.md:Leader will compare it's persistent state vs other members and rai
se a CORRUPT ALARM if there is a mismatch.
```

Additionally can you please ensure your commit is signed, by passing the `-s` parameter so the DCO check passes. i.e.

```bash
git reset --soft HEAD~1
# update other files
git commit -s -a -m "<message>"
```

**Comment by anand346** [comment]
okay sure , I'll fix all other instances

**Review by jmhbnz — COMMENTED** [review]
Thanks for updating all impacted files @anand346.

Can you please squash your changes to a single commit and ensure the commit is signed as above.

**Comment by jberkus** [comment]
@jmhbnz  or we could squash-merge it for them.  That's what I usually do.

Anyway, we can't merge until the deploy is working again.

**Comment by jmhbnz** [comment]
Hi @anand346 - Can you please take a look at the feedback above, we would love to merge your contribution! Thanks 🙏🏻

**Comment by jmhbnz** [comment]
Closing as no response from pr author.

**Pull request closed without merging**
