### PR TITLE
Cleanup/prep

### PR DESCRIPTION
**Pull request by nate-double-u**
- Updating Makefile
  - Updating DOCKER_IMG, removing unneeded lines
- removing data/faq.yaml and adding any missing questions to content/docs/current/faq.md
- removing "/docs /docs/{{ $latest }}" redirect as it appears not to be working, and we may want to use /docs in future as part of the docs TOC
- internal links updates
- adding list of generated metrics to metrics page
  - adding table of generated metrics
- updating /docs/current/metrics
- removing etcd-mixins from current as they are not Documentation and have been moved in the etcd-io/etcd repo.
- general links cleanup
- Updating versions system (drop-downs, "Versions of this doc",
deprecation warnings)
  - Versions links now default to a versions top level if there is no file associated with the current version in the linked to version

contributes to: https://github.com/etcd-io/website/issues/98
fixes: https://github.com/etcd-io/website/issues/90

### CODE REVIEW

**Comment by nate-double-u** [comment]
/cc @spzala @ptabor 

I've gone through and think that all the links in `content/docs/current` work -- with the exception of files that are referenced in the version menu that are not in other versions. I'm still not sure how to deal with the versioning system on that issue.

I'm also not sure about what to do about the following:
1. What should we do with the `content/docs/current/learning/lock` folder & content? I've removed it as it no longer makes sense as a README, and it was providing an example of how to do something as if the reader were still grabbing the info from the code repo. Instead of removing it, should we rework it to make more sense in the `learning` section?
2. Should we remove `content/docs/current/dev-guide/api-spec/swagger`? Is it used anywhere else? Is it documentation?

**Comment by nate-double-u** [comment]
Deploy preview:
https://deploy-preview-108--etcd.netlify.app
https://deploy-preview-108--etcd.netlify.app/docs/current/metrics/#generated-list-of-metrics

**Comment by nate-double-u** [comment]
I haven't moved any copy out of the config files yet, looking at how the site is built, and how the gRPC docsy conversion went, I think that the moving of the copy is a part of the work of doing that conversion.

**Comment by nate-double-u** [comment]
In my last force-push, I've redone the versioning system -- now, if a generated link in a drop-down, deprecation warning, or in the "Versions of this doc" list don't have a corresponding file in the target version, the link will default to the top level of the target version instead.

This has reduced our broken links reports from 1651 to 167. I'm still looking at the remaining broken links, but i think this fixes: https://github.com/etcd-io/website/issues/90

**Comment by nate-double-u** [comment]
Versioning fixes deploy previews:

Here are some pages that demonstrate how the new versioning system works (drop down menu, 'versions of this doc' line, and deprecation warning)

Every version has a FAQ page:
https://deploy-preview-108--etcd.netlify.app/docs/v2/faq/

Only version v2 and v3.1.12 have a Libraries and Tools page:
https://deploy-preview-108--etcd.netlify.app/docs/v2/libraries-and-tools/

Run etcd on Containel Linux with systemd was introduced in version v3.2.17:
https://deploy-preview-108--etcd.netlify.app/docs/v3.2.17/platforms/container-linux-systemd/

**Comment by spzala** [comment]
> /cc @spzala @ptabor
> 
> I've gone through and think that all the links in `content/docs/current` work -- with the exception of files that are referenced in the version menu that are not in other versions. I'm still not sure how to deal with the versioning system on that issue.
> 
> I'm also not sure about what to do about the following:
> 
>     1. What should we do with the `content/docs/current/learning/lock` folder & content? I've removed it as it no longer makes sense as a README, and it was providing an example of how to do something as if the reader were still grabbing the info from the code repo. Instead of removing it, should we rework it to make more sense in the `learning` section?
> 
>     2. Should we remove `content/docs/current/dev-guide/api-spec/swagger`? Is it used anywhere else? Is it documentation?

@nate-double-u yes, I would suggest to keep both for now and we can rethink it as a separate issue? Thanks!

**Review by spzala — COMMENTED** [review]
Where are putting deleted learning/lock files? I am sure you are taking care of it, but got little lost :) Thanks @nate-double-u 
Otherwise looks great.

**Comment by nate-double-u** [comment]
I'll put them back now -- I had taken them out when I made the comment. Next push will restore them

**Comment by spzala** [comment]
> I'll put them back now -- I had taken them out when I made the comment. Next push will restore them

OK, cool. Thanks!

**Comment by nate-double-u** [comment]
I'm marking this PR as "ready for review" as I'm not a fan of really big PRs, and this one is getting to be quite large. If we need to do more cleanup, we can do so with a new issue/PR.

**Review by spzala — APPROVED** [review]

**Comment by spzala** [comment]
> I'm marking this PR as "ready for review" as I'm not a fan of really big PRs, and this one is getting to be quite large. If we need to do more cleanup, we can do so with a new issue/PR.

Yup, sounds great. Thanks @nate-double-u

**Comment by nate-double-u** [comment]
Thanks Sahdev!

**Pull request merged**
