### PR TITLE
Add etcdadm in the tools list

### PR DESCRIPTION
**Pull request by spzala**
etcdadm is being actively developed and used.

Signed-off-by: Sahdev Zala <spzala@us.ibm.com>

### CODE REVIEW

**Comment by spzala** [comment]
cc @ahrtr @serathius

**Review by serathius — APPROVED** [review]

**Comment by spzala** [comment]
Thanks @serathius

**Comment by ahrtr** [comment]
Looks good.

**Comment by spzala** [comment]
Thanks @ahrtr

**Pull request merged**
