### PR TITLE
Render-link: trim whitespace from end template

### LINKED ISSUE #486: Render-link hook: back propagate change
The change introduced in https://github.com/notaryproject/notaryproject.dev/pull/40 should also be applied to this repo.

### PR DESCRIPTION
**Pull request by prashantrewar**
Fixes #486

### CODE REVIEW

**Review by jmhbnz — APPROVED** [review]
LGTM - Thanks @prashantrewar.

**Review by spzala — APPROVED** [review]
lgtm Thanks @prashantrewar cc @chalin @nate-double-u

**Review by ahrtr — APPROVED** [review]

**Pull request merged**
