### PR TITLE
improving text for transactional write

### PR DESCRIPTION
**Pull request by NavinShrinivas**
Pertains to issue #901. Doesn't have the GIF/video example attached. The text added in this PR is picked from the API documentation and I felt its relevant here as well.

### CODE REVIEW

**Comment by ivanvc** [comment]
Hi @NavinShrinivas, I just read about this PR in the #sig-etcd channel. Let's run the linter as a first pass, then I'll deliver a review :smile: 

/ok-to-test

**Comment by NavinShrinivas** [comment]
@ivanvc

**Comment by ivanvc** [comment]
@NavinShrinivas, sorry for the late response. Please refer to https://github.com/etcd-io/website/issues/901#issuecomment-2444888021

**Review by jmhbnz — CHANGES_REQUESTED** [review]
Hey @NavinShrinivas, @ivanvc - Thanks for raising this pr. Let's get this merged first given it was raised first.

Just one change needed, @NavinShrinivas can you please also update these changes to the 3.6 version of the tutorial: https://github.com/etcd-io/website/tree/main/content/en/docs/v3.6/tutorials

**Comment by NavinShrinivas** [comment]
@jmhbnz Have included in 3.6 as well

**Comment by jmhbnz** [comment]
> @jmhbnz Have included in 3.6 as well

Thanks @NavinShrinivas can you please address the lint failures in https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/etcd-io_website/905/pull-website-lint/1856660762336956416 so we can merge? Thanks!

**Comment by ivanvc** [comment]
@jmhbnz, could you do a pass to check the documentation's accuracy? If it is, we'll just need a squash in the commits.

**Review by jmhbnz — APPROVED** [review]

**Pull request merged**
