### PR TITLE
Simplifying docs section titles

### PR DESCRIPTION
**Pull request by nate-double-u**
contributes to: https://github.com/etcd-io/website/issues/178

### CODE REVIEW

**Comment by nate-double-u** [comment]
deploy preview: https://deploy-preview-199--etcd.netlify.app/docs/

**Comment by chalin** [comment]
I'm thinking that the section title updates should be done over `docsy` and then ported to `master`. We'll be able to better see the effect of the title updates that way -- effects on the breadcrumbs etc.

**Comment by nate-double-u** [comment]
> I'm thinking that the section title updates should be done over `docsy` and then ported to `master`.

See https://github.com/etcd-io/website/pull/202

**Comment by nate-double-u** [comment]
closing in favour of https://github.com/etcd-io/website/pull/213

**Pull request closed without merging**
